package com.elsd.board

/**
 * Switchboard vocabulary — full labels for voice / docs.
 * Home UI uses the 6 short panels: ADD · LAYERS · PRESETS · RANDOM · CLEAR · LIVE
 * (see SwitchboardActivity) — not these long strings on the root grid.
 */
enum class BoardVerb(val label: String, val short: String = label) {
    ADD_EFFECT("ADD EFFECT", "ADD"),
    REMOVE_EFFECT("REMOVE EFFECT", "REMOVE"),
    TOGGLE_EFFECT("TOGGLE EFFECT", "TOGGLE"),
    ADD_EFFECT_TIME("ADD EFFECT TIME", "IN"),
    REMOVE_EFFECT_TIME("REMOVE EFFECT TIME", "OUT"),
    PHASE_TIME("PHASE TIME", "PHASE"),
    PHASE_ON("PHASE ON", "PH ON"),
    PHASE_OFF("PHASE OFF", "PH OFF"),
    PRESETS("PRESETS", "PRESETS"),
    SAVE_PRESET("SAVE PRESET", "SAVE"),
    SAVE_PREFS("SAVE PREFS", "SAVE"),
    LOAD_PRESET("LOAD PRESET", "LOAD"),
    LOAD_PREFS("LOAD PREFS", "LOAD"),
    LIST_PRESETS("LIST PRESETS", "LIST"),
    DELETE_PRESET("DELETE PRESET", "DEL"),
    CLEAR_BOARD("CLEAR BOARD", "CLEAR"),
    RANDOM("RANDOM", "RANDOM"),
    AMY_ACTIONS_ON("AMY ACTIONS ON", "AMY ON"),
    AMY_ACTIONS_OFF("AMY ACTIONS OFF", "AMY OFF"),
    AMY_ANTICS("AMY ANTICS", "ANTICS"),
    SET_FRAMERATE("SET FRAMERATE", "FPS"),
    ENABLE_DROPPED_FRAMES("ENABLE DROPPED FRAMES", "DROPS ON"),
    DISABLE_DROPPED_FRAMES("DISABLE DROPPED FRAMES", "DROPS OFF"),
    UNLOCK_FRAMERATE("UNLOCK FRAMERATE", "FPS ∞"),
    GO_LIVE("GO LIVE", "LIVE"),
    BACK("BACK", "BACK"),
}
