package com.elsd.board

/**
 * Switchboard vocabulary — UI labels and voice share these verbs.
 */
enum class BoardVerb(val label: String) {
    ADD_EFFECT("ADD EFFECT"),
    REMOVE_EFFECT("REMOVE EFFECT"),
    TOGGLE_EFFECT("TOGGLE EFFECT"),
    ADD_EFFECT_TIME("ADD EFFECT TIME"),
    REMOVE_EFFECT_TIME("REMOVE EFFECT TIME"),
    PHASE_TIME("PHASE TIME"),
    PHASE_ON("PHASE ON"),
    PHASE_OFF("PHASE OFF"),
    SAVE_PRESET("SAVE PRESET"),
    LOAD_PRESET("LOAD PRESET"),
    CLEAR_BOARD("CLEAR BOARD"),
    RANDOM("RANDOM"),
    SET_FRAMERATE("SET FRAMERATE"),
    ENABLE_DROPPED_FRAMES("ENABLE DROPPED FRAMES"),
    DISABLE_DROPPED_FRAMES("DISABLE DROPPED FRAMES"),
    UNLOCK_FRAMERATE("UNLOCK FRAMERATE"),
    GO_LIVE("GO LIVE"),
    BACK("BACK"),
}
